import * as path from 'path';
import * as cdk from 'aws-cdk-lib/core';
import { Duration } from 'aws-cdk-lib/core';
import * as apiGateway from 'aws-cdk-lib/aws-apigateway';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as secretsManager from 'aws-cdk-lib/aws-secretsmanager';
import { PythonFunction, PythonFunctionProps } from '@aws-cdk/aws-lambda-python-alpha';
import { Construct } from 'constructs';

// Every Lambda is bundled from the same Python package and differs only by handler module,
// so shared code (e.g. the Battle Engine) is available to all of them without layers.
const BACKEND_DIR = path.join(__dirname, '..', 'backend');

export class PokemonAiBattleApiStack extends cdk.Stack {
  public readonly authorizerLambda: PythonFunction;
  public readonly healthLambda: PythonFunction;

  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // Generated by CloudFormation so it never appears in code or CI.
    // Read it from the Secrets Manager console to call the API.
    const sharedSecret = new secretsManager.Secret(this, 'ApiSharedSecret', {
      secretName: '/pokemon-ai-battle/api-shared-secret',
      description: 'Bearer token required on every Pokemon AI Battle API request',
      generateSecretString: { passwordLength: 48, excludePunctuation: true },
    });

    const commonLambdaProps: Omit<PythonFunctionProps, 'index'> = {
      entry: BACKEND_DIR,
      runtime: lambda.Runtime.PYTHON_3_14,
      handler: 'handler',
      memorySize: 128,
      timeout: Duration.seconds(5),
      bundling: {
        assetExcludes: [
          '.venv',
          'tests',
          '.pytest_cache',
          '**/__pycache__',
          'requirements-dev.txt',
        ],
      },
    };

    // Create the Lambda functions here.
    this.authorizerLambda = new PythonFunction(this, 'AuthorizerLambda', {
      ...commonLambdaProps,
      functionName: 'pokemon-battle-authorizer',
      index: 'pokemon_battle/handlers/authorizer.py',
      environment: { SHARED_SECRET_ARN: sharedSecret.secretArn },
    });
    sharedSecret.grantRead(this.authorizerLambda);

    this.healthLambda = new PythonFunction(this, 'HealthLambda', {
      ...commonLambdaProps,
      functionName: 'pokemon-battle-health',
      index: 'pokemon_battle/handlers/health.py',
    });

    const authorizer = new apiGateway.TokenAuthorizer(this, 'SharedSecretAuthorizer', {
      handler: this.authorizerLambda,
      identitySource: apiGateway.IdentitySource.header('Authorization'),
      resultsCacheTtl: Duration.minutes(5),
    });

    const apiGw = new apiGateway.RestApi(this, 'PokemonAiBattleApi', {
      restApiName: 'PokemonAiBattleApi',
      // Every route requires the shared secret unless it explicitly opts out.
      defaultMethodOptions: {
        authorizer,
        authorizationType: apiGateway.AuthorizationType.CUSTOM,
      },
      defaultCorsPreflightOptions: {
        allowOrigins: apiGateway.Cors.ALL_ORIGINS,
        allowMethods: apiGateway.Cors.ALL_METHODS,
        allowHeaders: ['Content-Type', 'Authorization'],
      },
    });

    // Errors generated by API Gateway itself (e.g. a 401 from the authorizer) don't pass through
    // a Lambda, so they need CORS headers here or a browser reports a CORS error instead of the 401.
    for (const [id, type] of [
      ['Default4xx', apiGateway.ResponseType.DEFAULT_4XX],
      ['Default5xx', apiGateway.ResponseType.DEFAULT_5XX],
    ] as const) {
      apiGw.addGatewayResponse(id, {
        type,
        responseHeaders: { 'Access-Control-Allow-Origin': "'*'" },
      });
    }

    // Create routes here and assign Lambda functions to them.
    const health = apiGw.root.addResource('health');
    health.addMethod('GET', new apiGateway.LambdaIntegration(this.healthLambda));
  }
}
